defaults:
  - model: cnn
  - optimizer: sgd
  - train: default
  - dataset: cat_n_dog

seed: 100
device: cuda
model_name: "cat_dog_cnn"


cat_n_dog:
  path_cat: "cat_n_dog/img/original/cat/*.jpg"
  path_dog: "cat_n_dog/img/original/dog/*.jpg"
  target_size: 128
  split: [0.7, 0.1, 0.2]

model:
  name: "CNN"
  input_size: 128
  num_classes: 2

optimizer:
  name: sgd
  lr: 0.001
  momentum: 0.9

default:
  batch_size: 32
  epochs: 30

